// No auth events or network calls: UI-only Settings controller fixture.
const blocked = async () => { throw new Error('Preview only: Firebase actions disabled'); };
export const EmailAuthProvider = { credential: () => ({}) };
export const initializeApp = () => ({});
export const getAuth = () => ({ currentUser: null });
export const onAuthStateChanged = () => () => {};
export const updateEmail = blocked;
export const updatePassword = blocked;
export const updatePhoneNumber = blocked;
export const signOut = blocked;
export const deleteUser = blocked;
export const reauthenticateWithCredential = blocked;
export const multiFactor = blocked;
export const getFirestore = () => ({});
export const doc = () => ({});
export const getDoc = blocked;
export const setDoc = blocked;
export const updateDoc = blocked;
export const deleteDoc = blocked;
export const collection = () => ({});
export const onSnapshot = () => () => {};
export const addDoc = blocked;
export const query = () => ({});
export const where = () => ({});
export const orderBy = () => ({});
export const serverTimestamp = () => ({});
export const getStorage = () => ({});
export const ref = () => ({});
export const uploadBytes = blocked;
export const getDownloadURL = blocked;
export const deleteObject = blocked;
